### ISSUE TITLE
Why include CocoaHeads?

### ISSUE THREAD

**Issue by arielelkin** [lashkhi/iosCommunities#2]
CocoaHeads is already federated here:
http://cocoaheads.org/

Maybe this repo should just link to their website rather than duplicating a listing of their meetups.

**Comment by lashkhi** [comment]
@arielelkin I'm not sure that all communities are being updated in time, so for example you can't easily find twitter/facebook links from that site 🤔. But I'll make a Worldwide section, where we can put it 🙂

**Comment by arielelkin** [comment]
They are usually updated in time (can you think of a CocoaHeads community that's not in their list?). They don't publish a twitter/facebook link for their communities but I'm _confident_ that CocoaHeads attendees are able to figure out what a specific community's twitter handle is. They just need to figure out if it exists in the first place. 

But yeah, I don't see why it's a good idea for this repo to _duplicate_ the listing of CocoaHeads communities.

**Comment by lashkhi** [comment]
@arielelkin I'm totally sure CocoaHeads attendees will be able to find twitter/facebook/slack communities, the question is just isn't it just more convenient to find them out right from here, instead of searching web? 
Anyway, I'm not trying to urge, if the community decides to keep only the global link— I'll remove them🙂 Let's just wait for some time, until more people contribute and discover this page 🙂
